using System.Collections.Generic;

namespace Archipelagarten2.Constants
{
    public static class MonstermonCards
    {
        public static readonly Dictionary<int, string> CardNames = new()
        {
            { 0, "Celestial Slug" },
            { 1, "Hard Boogar" },
            { 2, "Bucket O Water" },
            { 3, "Pale Tuna" },
            { 4, "Ultralodon" },
            { 5, "Carnivorous Nimbus" },
            { 6, "Tiny Squid" },
            { 7, "Coral That Looks Like Hand" },
            { 8, "Hermit Frog" },
            { 9, "Castle of Sand" },
            { 10, "Man on Fire" },
            { 11, "Chair of Spikes" },
            { 12, "Cigaretmon" },
            { 13, "Dune Worm" },
            { 14, "Stressed Llama" },
            { 15, "Cyclops Duckling" },
            { 16, "Teenage Mutant Zombie" },
            { 17, "Lonely Dragon" },
            { 18, "Million-Head Hydra" },
            { 19, "Dab Hero" },
            { 20, "Monstrous Flytrap" },
            { 21, "The Tallest Tree" },
            { 22, "Chill Stump" },
            { 23, "Gnome of Garden" },
            { 24, "Ofaka Tornado" },
            { 25, "Literally Grass" },
            { 26, "Doodoo Bug" },
            { 27, "Mystical Tomato" },
            { 28, "Hissing Fauna" },
            { 29, "Legendary Sword" },
            { 30, "Golden Dewdrop" },
            { 31, "Zen Octopus" },
            { 32, "Forbidden Book" },
            { 33, "Marshmallow" },
            { 34, "Pot of Grease" },
            { 35, "Lamb With Cleaver" },
            { 36, "Treasure Chest" },
            { 37, "Mr. Nice Guy" },
            { 38, "The Slurper" },
            { 39, "Rare Jewel" },
            { 40, "Onion" },
            { 41, "Killer Eye" },
            { 42, "Purple Plush" },
            { 43, "Spiky Flim Flam" },
            { 44, "Monster Ghost" },
            { 45, "Knight Who Turned Evil" },
            { 46, "Evil Thwarter" },
            { 47, "Mysterious Package" },
            { 48, "Oglebop Ogre" },
            { 49, "Dank Magician" },
        };
    }
}
